//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitWro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string CategoryEvent { get; set; }
        public string NameEvent { get; set; }
        public string DescriptionEvent { get; set; }
        public string DateEvent { get; set; }
        public string Price { get; set; }
        public string ImageEvent { get; set; }
        public string ThumbEvent { get; set; }
        public string Website { get; set; }
        public Nullable<int> Removed { get; set; }
        public Nullable<int> IsFavourite { get; set; }
        public int AddressId { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
