//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitWro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int PlaceId { get; set; }
        public string CategoryPlace { get; set; }
        public string NamePlace { get; set; }
        public string DescriptionPlace { get; set; }
        public string Phone { get; set; }
        public string Mark { get; set; }
        public string ImagePlace { get; set; }
        public string ThumbPlace { get; set; }
        public Nullable<int> Removed { get; set; }
        public Nullable<int> IsFavourite { get; set; }
        public int AddressId { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
